version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t node-js-server .
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - run:
          name: list image
          command: docker image list
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 --name node-js-server-container node-js-server
      - run:
          name: Wait for the server to start
          command: sleep 5
      - run:
          name: Test the application with wget
          command: wget -qO- http://localhost:8080

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
