version: 2.1

orbs:
  docker: circleci/docker@2.0

jobs:
  build-and-push:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: node-js-server
          tag: latest
      - docker/publish:
          image: node-js-server
          tag: latest
          registry: docker.io
          username: flqvvperso
          password: dckr_pat_zGvXUh5A93gN4RM7K5MAheogFyE

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
