version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  build-docker-image-only:
    jobs:
      - checkout
      - docker/publish:
          dockerfile: Dockerfile
          image: flqvvperso/node-js-server
          auth:
            username: flqvvperso
            password: dckr_pat_-wwb8xvYBuqvvAnSigaE9aMWgO8
