version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-and-push:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: node:14
          dockerfile: Dockerfile
          tag: flqvvperso/node-js-server:latest
      - docker/push:
          image: flqvvperso/node-js-server:latest

workflows:
  push:
    jobs:
      - build-and-push
