version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: flqvvperso/node-js-server
          update-description: true
          docker-username: flqvvperso
          docker-password: dckr_pat_-wwb8xvYBuqvvAnSigaE9aMWgO8
