version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t node-js-server .
      - run:
          name: list image
          command: docker image list
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 --name node-js-server-container node-js-server
      - run:
          name: Wait for the server to start
          command: sleep 5
      - run:
          name: Test the application with wget
          command: wget -qO- http://localhost:8080
      - run:
          name: Login to Docker Hub
          command: echo dckr_pat_wlYQbI6MPCwyzb_P1rX2OQyVrsE | docker login -u flqvvperso --password-stdin
      - run:
          name: Tag Docker image
          command: docker tag node-js-server flqvvperso/node-js-server:latest
      - run:
          name: Push Docker image to Docker Hub
          command: docker push flqvvperso/node-js-server:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
