version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/publish:
        image: flqvvperso/node-server
        update-description: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
